name: Compilar APK con Buildozer

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v4

    - name: Instalar dependencias de Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip python3-dev \
            autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
            libncursesw5-dev cmake libffi-dev libssl-dev

    - name: Instalar Buildozer y Cython
      run: |
        pip3 install --upgrade pip
        pip3 install --user Cython==0.29.36 buildozer

    - name: Asegurar PATH para buildozer
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Compilar APK
      run: buildozer -v android debug

    - name: Subir APK generado
      uses: actions/upload-artifact@v4
      with:
        name: paquete-apk
        path: bin/*.apk
